import Head from "next/head";
import React from "react";
import ContactHeader from "@/components/ContactHeader/ContactHeader";
import ContactForm from "@/components/ContactForm/ContactForm";

const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Sujay | Contact Me 📱</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactHeader />
      <ContactForm />
    </>
  );
};

export default ContactPage;
