import Head from "next/head";
import styled from "styled-components";
import Header from "@/components/Header/Header";
import About from "@/components/About/About";
import Skills from "@/components/Skills/Skills";
import Projects from "@/components/Projects/Projects";
import Blog from "@/components/Blog/Blog";
import Footer from "@/components/Footer/Footer";
import { media } from "@/utils/device";

const StyledContainer = styled.div`
  margin: 0;

  @media ${media.laptopLarge} {
    margin: 0 80px;
  }
`;

export default function Home() {
  return (
    <StyledContainer>
      <Head>
        <title>Sujay | The Devops Guy 😎</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Skills />
      <Projects />
      <Blog />
      <Footer />
    </StyledContainer>
  );
}
